### ISSUE TITLE
Is this code is for frontend or it's node.js?

### ISSUE THREAD

**Issue by Catsvilles** [audiojs/audio-buffer-from#7]
Yes, yes, I know, I'm really sorry for asking this silly question. But the thing is I'm just getting started with Audio API and JS and so on. It's just one of the arguments we pass is AudioContext, which ofc is intended to work in the browser only and yet we use "require()" from what I know this is node.js stuff. What I'm missing here? Will be really happy to hear any answers on how actually to run this, the lib possibly will save my life! :) Thank you!

P.S. tried to run in the browser as module, no success at all, hehe.

**Comment by darrendahl** [comment]
I always have the same question and concern when coming to packages such as these. 

Sometimes i see a `-client` version of packages and it works for the browser when it is a nodejs package with `require` syntax. It is always surprising to me to see so many node packages for webaudio api when it is a browser/client specific API. I'm not sure how this would even work in node (maybe I'm just dumb!). Anyway maybe I'll create an `audio-buffer-from-client` package because this would be a super useful module for the browser

**Comment by Catsvilles** [comment]
@darrendahl at this point it's clear to me that this is all about node.js here, since it's made for their [Node.js implementation of Web audio API](https://github.com/audiojs/web-audio-api) too bad it's dead and unsupported though :)
